(ns interop.native-base
  (:refer-clojure :exclude [List]))

(def NativeBase (js/require "native-base"))

(def getTheme (.-getTheme NativeBase))
(def variables (.-variables NativeBase))
(def StyleProvider (.-StyleProvider NativeBase))
(def connectStyle (.-connectStyle NativeBase))
(def Drawer (.-Drawer NativeBase))
(def Button (.-Button NativeBase))
(def IconNB (.-IconNB NativeBase))
(def Icon (.-Icon NativeBase))
(def Header (.-Header NativeBase))
(def Form (.-Form NativeBase))
(def InputGroup (.-InputGroup NativeBase))
(def Input (.-Input NativeBase))
(def Title (.-Title NativeBase))
(def Fab (.-Fab NativeBase))
(def Left (.-Left NativeBase))
(def Right (.-Right NativeBase))
(def Body (.-Body NativeBase))
(def Badge (.-Badge NativeBase))
(def CheckBox (.-CheckBox NativeBase))
(def Radio (.-Radio NativeBase))
(def Thumbnail (.-Thumbnail NativeBase))
(def Card (.-Card NativeBase))
(def CardItem (.-CardItem NativeBase))
(def H1 (.-H1 NativeBase))
(def H2 (.-H2 NativeBase))
(def H3 (.-H3 NativeBase))
(def Spinner (.-Spinner NativeBase))
(def Switch (.-Switch NativeBase))
(def Container (.-Container NativeBase))
(def Content (.-Content NativeBase))
(def Footer (.-Footer NativeBase))
(def Tab (.-Tab NativeBase))
(def Tabs (.-Tabs NativeBase))
(def FooterTab (.-FooterTab NativeBase))
(def Picker (.-Picker NativeBase))
(def PickerItem (.-Item (.-Picker NativeBase)))
(def List (.-List NativeBase))
(def ListItem (.-ListItem NativeBase))
(def Separator (.-Separator NativeBase))
(def DeckSwiper (.-DeckSwiper NativeBase))
(def Item (.-Item NativeBase))
(def Subtitle (.-Subtitle NativeBase))
(def Label (.-Label NativeBase))
(def Textarea (.-Textarea NativeBase))
(def Col (.-Col NativeBase))
(def Row (.-Row NativeBase))
(def Grid (.-Grid NativeBase))
(def Text (.-Text NativeBase))
(def TabContent (.-TabContent NativeBase))
(def View (.-View NativeBase))
(def Toast (.-Toast NativeBase))
(def ScrollableTab (.-ScrollableTab NativeBase))
(def ActionSheet (.-ActionSheet NativeBase))
(def TabHeading (.-TabHeading NativeBase))
(def TabContainer (.-TabContainer NativeBase))
(def DefaultTabBar (.-DefaultTabBar NativeBase))
(def Segment (.-Segment NativeBase))
(def Root (.-Root NativeBase))
(def SwipeRow (.-SwipeRow NativeBase))
(def mapPropsToStyleNames (.-mapPropsToStyleNames NativeBase))

(defn toast-show
  [opts]
  (.show Toast (clj->js opts)))