(ns interop.react-native
  (:require [reagent.core :as r]
            [interop.react :as react]))

(set! *warn-on-infer* true)

(def ReactNative ^js/ReactNative (js/require "react-native"))

(def AccessibilityInfo (.-AccessibilityInfo ReactNative))
(def ActivityIndicator (.-ActivityIndicator ReactNative))
(def activity-indicator (r/adapt-react-class ActivityIndicator))
(def ART (.-ART ReactNative))
(def Button (.-Button ReactNative))
(def button (r/adapt-react-class Button))
(def CheckBox (.-CheckBox ReactNative))
(def DatePickerIOS (.-DatePickerIOS ReactNative))
(def date-picker-ios (r/adapt-react-class DatePickerIOS))
(def DrawerLayoutAndroid (.-DrawerLayoutAndroid ReactNative))
(def FlatList (.-FlatList ReactNative))
(def flat-list (r/adapt-react-class FlatList))
(def FlatList* (react/create-factory FlatList))
(def Image (.-Image ReactNative))
(def image (r/adapt-react-class Image))
(def ImageBackground (.-ImageBackground ReactNative))
(def image-background (r/adapt-react-class ImageBackground))
(def ImageEditor (.-ImageEditor ReactNative))
;(def ImageStore (.-ImageStore ReactNative))
(def KeyboardAvoidingView (.-KeyboardAvoidingView ReactNative))
;(def MaskedViewIOS (.-MaskedViewIOS ReactNative))
(def Modal (.-Modal ReactNative))
(def modal (r/adapt-react-class Modal))
(def Picker (.-Picker ReactNative))
(def picker (r/adapt-react-class Picker))
(def Item (.-Item Picker))
(def item (r/adapt-react-class Item))
(def PickerIOS (.-PickerIOS ReactNative))
(def ProgressBarAndroid (.-ProgressBarAndroid ReactNative))
(def ProgressViewIOS (.-ProgressViewIOS ReactNative))
(def SafeAreaView (.-SafeAreaView ReactNative))
(def safe-area-view (r/adapt-react-class SafeAreaView))
(def ScrollView (.-ScrollView ReactNative))
(def scroll-view (r/adapt-react-class ScrollView))
(def SectionList (.-SectionList ReactNative))
(def section-list (r/adapt-react-class SectionList))
(def SegmentedControlIOS (.-SegmentedControlIOS ReactNative))
;(def Slider (.-Slider ReactNative))
(def SnapshotViewIOS (.-SnapshotViewIOS ReactNative))
(def Switch (.-Switch ReactNative))
(def switch (r/adapt-react-class Switch))
(def RefreshControl (.-RefreshControl ReactNative))
(def StatusBar (.-StatusBar ReactNative))
(def status-bar (r/adapt-react-class StatusBar))
(def SwipeableFlatList (.-SwipeableFlatList ReactNative))
(def TabBarIOS (.-TabBarIOS ReactNative))
(def Text (.-Text ReactNative))
(def text (r/adapt-react-class Text))
(def TextInput (.-TextInput ReactNative))
(def text-input (r/adapt-react-class TextInput))
(def ToastAndroid (.-ToastAndroid ReactNative))
(def ToolbarAndroid (.-ToolbarAndroid ReactNative))
(def Touchable (.-Touchable ReactNative))
(def touchable (r/adapt-react-class Touchable))
(def TouchableHighlight (.-TouchableHighlight ReactNative))
(def touchable-highlight (r/adapt-react-class TouchableHighlight))
(def TouchableNativeFeedback (.-TouchableNativeFeedback ReactNative))
(def touchable-native-feedback (r/adapt-react-class TouchableNativeFeedback))
(def TouchableOpacity (.-TouchableOpacity ReactNative))
(def touchable-opacity (r/adapt-react-class TouchableOpacity))
(def TouchableWithoutFeedback (.-TouchableWithoutFeedback ReactNative))
(def touchable-without-feedback (r/adapt-react-class TouchableWithoutFeedback))
(def View (.-View ReactNative))
(def view (r/adapt-react-class View))
(def ViewPagerAndroid (.-ViewPagerAndroid ReactNative))
(def VirtualizedList (.-VirtualizedList ReactNative))
(def WebView (.-WebView ReactNative))
(def ActionSheetIOS (.-ActionSheetIOS ReactNative))
(def Alert (.-Alert ReactNative))
(def AlertIOS (.-AlertIOS ReactNative))
(def Animated (.-Animated ReactNative))
(def AnimatedView (.-View Animated))
(def AnimatedText (.-Text Animated))
(def AnimatedValue (.-Value Animated))
(def AppRegistry (.-AppRegistry ReactNative))
(def AppState (.-AppState ReactNative))
(def AsyncStorage ^AsyncStorage (.-AsyncStorage ReactNative))
(defn async-storage-set-item [k v cb] (.setItem AsyncStorage k v cb))
(defn async-storage-get-item [k cb] (.getItem AsyncStorage k cb))
(defn async-storage-remove-item [k cb] (.removeItem AsyncStorage k cb))
(def BackAndroid (.-BackAndroid ReactNative))
(def BackHandler (.-BackHandler ReactNative))
(def CameraRoll (.-CameraRoll ReactNative))
(def Clipboard (.-Clipboard ReactNative))
(def DatePickerAndroid (.-DatePickerAndroid ReactNative))
(def date-picker-android (r/adapt-react-class DatePickerAndroid))
(def DeviceInfo (.-DeviceInfo ReactNative))
(def Dimensions (.-Dimensions ReactNative))
(def Easing (.-Easing ReactNative))
(def findNodeHandle (.-findNodeHandle ReactNative))
(def I18nManager (.-I18nManager ReactNative))
(def ImagePickerIOS (.-ImagePickerIOS ReactNative))
(def InteractionManager (.-InteractionManager ReactNative))
(def Keyboard (.-Keyboard ReactNative))
(def LayoutAnimation (.-LayoutAnimation ReactNative))
(def Linking (.-Linking ReactNative))
(def NativeEventEmitter (.-NativeEventEmitter ReactNative))
;(def NetInfo (.-NetInfo ReactNative))
(def PanResponder (.-PanResponder ReactNative))
(def PermissionsAndroid (.-PermissionsAndroid ReactNative))
(def PixelRatio (.-PixelRatio ReactNative))
(def Settings (.-Settings ReactNative))
(def Share (.-Share ReactNative))
(def StatusBarIOS (.-StatusBarIOS ReactNative))
(def StyleSheet (.-StyleSheet ReactNative))
(def Systrace (.-Systrace ReactNative))
(def TimePickerAndroid (.-TimePickerAndroid ReactNative))
(def TVEventHandler (.-TVEventHandler ReactNative))
(def UIManager (.-UIManager ReactNative))
(def unstable_batchedUpdates (.-unstable_batchedUpdates ReactNative))
(def Vibration (.-Vibration ReactNative))
(def VibrationIOS (.-VibrationIOS ReactNative))
(def YellowBox (.-YellowBox ReactNative))
(def DeviceEventEmitter (.-DeviceEventEmitter ReactNative))
(def NativeAppEventEmitter (.-NativeAppEventEmitter ReactNative))
(def NativeModules (.-NativeModules ReactNative))
(def Platform (.-Platform ReactNative))
(def ios? (= "ios" (.-OS Platform)))
(def android? (= "android" (.-OS Platform)))
(def processColor (.-processColor ReactNative))
(def requireNativeComponent (.-requireNativeComponent ReactNative))
(def takeSnapshot (.-takeSnapshot ReactNative))
(def ColorPropType (.-ColorPropType ReactNative))
(def EdgeInsetsPropType (.-EdgeInsetsPropType ReactNative))
(def PointPropType (.-PointPropType ReactNative))
(def ViewPropTypes (.-ViewPropTypes ReactNative))

(defn blur-currently-focused-field
  []
  (let [text-input-state (.-State TextInput)]
    (.blurTextInput text-input-state (.currentlyFocusedField text-input-state))))

(defn focused-text-input
  []
  (.currentlyFocusedField (.-State TextInput)))

(defn blur-and-callback
  [cb]
  (let [id (focused-text-input)
        iid (atom nil)]
    (if id
      (do (blur-currently-focused-field)
          (reset! iid (js/setInterval
                        (fn []
                          (when (not= id (focused-text-input))
                            (js/clearInterval @iid)
                            (js/setTimeout cb 10)))
                        10)))
      (cb))))

(defn alert [title]
  (.alert Alert title))